app = "olympo-login"
primary_region = "gru"

[build]
dockerfile = "Dockerfile"

[env]
SERVER_PORT = "8082"
SPRING_PROFILES_ACTIVE = "docker"
JAVA_OPTS = "-Xmx200m -Xms64m -XX:+UseSerialGC"

[[services]]
internal_port = 8082
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[vm]
memory = "512mb"
cpu_kind = "shared"
cpus = 1
